// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8oIrrryEKUZOu79Jf6_dmem6ZQpaNXeE',
    appId: '1:570999462191:web:61b2862294e210dea669da',
    messagingSenderId: '570999462191',
    projectId: 'r2ait-f7ec3',
    authDomain: 'r2ait-f7ec3.firebaseapp.com',
    storageBucket: 'r2ait-f7ec3.firebasestorage.app',
    measurementId: 'G-BHEM60MVV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlpH1qMo5Ln8tBgY1P8xoyhgm0NJzTsQ',
    appId: '1:570999462191:android:207055f1eccd180da669da',
    messagingSenderId: '570999462191',
    projectId: 'r2ait-f7ec3',
    storageBucket: 'r2ait-f7ec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDntf8uoU48XuR8p5-F1TcTEYoMK0AYn60',
    appId: '1:570999462191:ios:f208b48b494324ada669da',
    messagingSenderId: '570999462191',
    projectId: 'r2ait-f7ec3',
    storageBucket: 'r2ait-f7ec3.firebasestorage.app',
    iosClientId: '570999462191-hvfsdo5moinfd4j2b3gjjigsokre77jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.r2aitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDntf8uoU48XuR8p5-F1TcTEYoMK0AYn60',
    appId: '1:570999462191:ios:f208b48b494324ada669da',
    messagingSenderId: '570999462191',
    projectId: 'r2ait-f7ec3',
    storageBucket: 'r2ait-f7ec3.firebasestorage.app',
    iosClientId: '570999462191-hvfsdo5moinfd4j2b3gjjigsokre77jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.r2aitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8oIrrryEKUZOu79Jf6_dmem6ZQpaNXeE',
    appId: '1:570999462191:web:e3c79ee647ba121da669da',
    messagingSenderId: '570999462191',
    projectId: 'r2ait-f7ec3',
    authDomain: 'r2ait-f7ec3.firebaseapp.com',
    storageBucket: 'r2ait-f7ec3.firebasestorage.app',
    measurementId: 'G-9PDMZ8FF1K',
  );

}